name: .NET Core

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0
    
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore 
    - name: build lib
      run: dotnet build Lib\redis-csharp.csproj --configuration Release --no-restore /p:ContinuousIntegrationBuild=true
    - name: build tests project
      run: dotnet build Tests\Tests.csproj --configuration Release --no-restore /p:ContinuousIntegrationBuild=true
    - name: Test
      run: dotnet test Tests\bin\Debug\Tests.dll --no-restore --verbosity normal
